### ISSUE TITLE
ресайз картинки

### ISSUE THREAD

**Issue by tsarevfs** [LisGein/linuxLessons#5]
1. Label не владеет картинкой. Когда QImage разрушается, label начинает рисовать какую-то фигню. Поэтому храни ее пока живет окно.
   2 Картинку можно растягивать на весь label: scaled_img = img.scaled(

**Comment by LisGein** [comment]
Сделала чтобы QImage не разрушался. 
Действительно нужно сделать, чтобы картинку можно было растягивать?
